// products.js — StyleNest product database (30 products)
// Images use Picsum seeded placeholders so every product has a stable,
// unique-looking photo without requiring real product photography.

const PRODUCTS = [
  { id: 1, name: "Classic Crew Neck Tee", section: "Men", category: "T-Shirts", price: 24.99, oldPrice: 34.99, discount: 29, rating: 4.6, reviews: 128, description: "A soft, breathable everyday tee cut from combed cotton. Holds its shape wash after wash.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "White", "Navy"], stock: 42, image: "https://images.pexels.com/photos/17630522/pexels-photo-17630522.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 2, name: "Pique Polo Shirt", section: "Men", category: "Polo Shirts", price: 39.99, oldPrice: 49.99, discount: 20, rating: 4.4, reviews: 76, description: "Classic pique-knit polo with a tailored fit and ribbed collar for a sharp, casual look.", sizes: ["S", "M", "L", "XL"], colors: ["Forest", "White", "Burgundy"], stock: 31, image: "https://images.pexels.com/photos/3779453/pexels-photo-3779453.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 3, name: "Slim Fit Jeans", section: "Men", category: "Jeans", price: 59.99, oldPrice: 79.99, discount: 25, rating: 4.7, reviews: 204, description: "Stretch denim with a modern slim taper. Fades and washes for a broken-in feel from day one.", sizes: ["30", "32", "34", "36"], colors: ["Indigo", "Black"], stock: 58, image: "https://images.pexels.com/photos/6764007/pexels-photo-6764007.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 4, name: "Fleece Pullover Hoodie", section: "Men", category: "Hoodies", price: 44.99, oldPrice: 59.99, discount: 25, rating: 4.8, reviews: 312, description: "Heavyweight fleece hoodie with a brushed interior for all-day warmth and comfort.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Charcoal", "Olive"], stock: 47, image: "https://images.pexels.com/photos/2058661/pexels-photo-2058661.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 5, name: "Bomber Jacket", section: "Men", category: "Jackets", price: 89.99, oldPrice: 119.99, discount: 25, rating: 4.5, reviews: 94, description: "Lightweight bomber with a ribbed collar and cuffs. The layering piece your rotation is missing.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Khaki"], stock: 22, image: "https://images.pexels.com/photos/207081/pexels-photo-207081.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 6, name: "Two-Piece Wool Suit", section: "Men", category: "Suits", price: 249.99, oldPrice: 329.99, discount: 24, rating: 4.9, reviews: 41, description: "Half-canvas wool-blend suit, tailored for a modern silhouette. Built for boardrooms and beyond.", sizes: ["38", "40", "42", "44"], colors: ["Charcoal", "Navy"], stock: 14, image: "https://images.pexels.com/photos/652352/pexels-photo-652352.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 7, name: "Graphic Print Tee", section: "Men", category: "T-Shirts", price: 27.99, oldPrice: 32.99, discount: 15, rating: 4.3, reviews: 65, description: "Statement graphic tee on heavyweight cotton, screen-printed for a lasting finish.", sizes: ["S", "M", "L", "XL"], colors: ["White", "Black"], stock: 39, image: "https://images.pexels.com/photos/157646/pexels-photo-157646.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 8, name: "Wrap Midi Dress", section: "Women", category: "Dresses", price: 69.99, oldPrice: 89.99, discount: 22, rating: 4.8, reviews: 156, description: "A flattering wrap silhouette in flowing crepe. Transitions effortlessly from desk to dinner.", sizes: ["XS", "S", "M", "L"], colors: ["Rosewood", "Black"], stock: 28, image: "https://images.pexels.com/photos/18192196/pexels-photo-18192196.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 9, name: "Silk Button-Up Blouse", section: "Women", category: "Blouses", price: 54.99, oldPrice: 69.99, discount: 21, rating: 4.6, reviews: 88, description: "Fluid silk-blend blouse with mother-of-pearl buttons. A wardrobe staple with quiet polish.", sizes: ["XS", "S", "M", "L"], colors: ["Ivory", "Blush"], stock: 33, image: "https://images.pexels.com/photos/26934505/pexels-photo-26934505.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 10, name: "High-Waist Skinny Jeans", section: "Women", category: "Jeans", price: 54.99, oldPrice: 74.99, discount: 27, rating: 4.7, reviews: 189, description: "Sculpting stretch denim with a flattering high-rise waist and cropped ankle length.", sizes: ["24", "26", "28", "30", "32"], colors: ["Indigo", "Black"], stock: 51, image: "https://images.pexels.com/photos/13666118/pexels-photo-13666118.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 11, name: "Structured Tote Bag", section: "Women", category: "Handbags", price: 79.99, oldPrice: 99.99, discount: 20, rating: 4.5, reviews: 72, description: "Vegan-leather tote with a structured base and interior organization for everyday carry.", sizes: [], colors: ["Tan", "Black"], stock: 19, image: "https://images.pexels.com/photos/2433862/pexels-photo-2433862.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 12, name: "Pointed Stiletto Heels", section: "Women", category: "Heels", price: 64.99, oldPrice: 84.99, discount: 24, rating: 4.4, reviews: 103, description: "Sleek pointed-toe stilettos with a cushioned footbed built for real-world wear.", sizes: ["36", "37", "38", "39", "40"], colors: ["Black", "Nude"], stock: 26, image: "https://images.pexels.com/photos/134064/pexels-photo-134064.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 13, name: "Tailored Blazer", section: "Women", category: "Blazers", price: 94.99, oldPrice: 124.99, discount: 24, rating: 4.7, reviews: 61, description: "Sharp single-breasted blazer with a nipped waist. Layers over anything, elevates everything.", sizes: ["XS", "S", "M", "L"], colors: ["Black", "Camel"], stock: 21, image: "https://images.pexels.com/photos/982585/pexels-photo-982585.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 14, name: "Floral Summer Dress", section: "Women", category: "Dresses", price: 49.99, oldPrice: 64.99, discount: 23, rating: 4.5, reviews: 97, description: "Lightweight floral-print dress with a flutter sleeve and swishy midi hem.", sizes: ["XS", "S", "M", "L"], colors: ["Coral Print"], stock: 34, image: "https://images.pexels.com/photos/667208/pexels-photo-667208.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 15, name: "Kids Graphic T-Shirt", section: "Kids", category: "Kids Clothing", price: 16.99, oldPrice: 21.99, discount: 23, rating: 4.6, reviews: 54, description: "Soft cotton tee with a fun printed graphic. Machine washable and built for play.", sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"], colors: ["Sky Blue", "Yellow"], stock: 45, image: "https://images.pexels.com/photos/14325735/pexels-photo-14325735.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 16, name: "Kids Denim Overalls", section: "Kids", category: "Kids Clothing", price: 29.99, oldPrice: 37.99, discount: 21, rating: 4.7, reviews: 38, description: "Adjustable-strap denim overalls with reinforced knees for everyday adventures.", sizes: ["2-3Y", "4-5Y", "6-7Y"], colors: ["Light Wash"], stock: 27, image: "https://images.pexels.com/photos/8922895/pexels-photo-8922895.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 17, name: "Kids Canvas Sneakers", section: "Kids", category: "Shoes", price: 22.99, oldPrice: 27.99, discount: 18, rating: 4.5, reviews: 49, description: "Lightweight canvas sneakers with a hook-and-loop strap for easy on and off.", sizes: ["10", "11", "12", "13", "1"], colors: ["White", "Red"], stock: 36, image: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 18, name: "Men's Running Sneakers", section: "Shoes", category: "Sneakers", price: 74.99, oldPrice: 94.99, discount: 21, rating: 4.8, reviews: 221, description: "Responsive foam midsole and breathable mesh upper built for daily mileage.", sizes: ["40", "41", "42", "43", "44", "45"], colors: ["Black/Grey", "Blue/White"], stock: 40, image: "https://images.pexels.com/photos/8373048/pexels-photo-8373048.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 19, name: "Women's Chunky Sneakers", section: "Shoes", category: "Sneakers", price: 69.99, oldPrice: 89.99, discount: 22, rating: 4.6, reviews: 134, description: "Platform chunky sneakers pairing street style with genuine all-day comfort.", sizes: ["36", "37", "38", "39", "40"], colors: ["White", "Pastel Pink"], stock: 29, image: "https://images.pexels.com/photos/5172731/pexels-photo-5172731.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 20, name: "Ankle Strap Heels", section: "Shoes", category: "Heels", price: 59.99, oldPrice: 79.99, discount: 25, rating: 4.3, reviews: 67, description: "Elegant ankle-strap heels with a block heel for stability without sacrificing style.", sizes: ["36", "37", "38", "39"], colors: ["Black", "Burgundy"], stock: 23, image: "https://images.pexels.com/photos/1451760/pexels-photo-1451760.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 21, name: "Leather Chelsea Boots", section: "Shoes", category: "Boots", price: 99.99, oldPrice: 129.99, discount: 23, rating: 4.7, reviews: 88, description: "Genuine leather Chelsea boots with an elastic side panel and pull tab for easy wear.", sizes: ["40", "41", "42", "43", "44"], colors: ["Black", "Brown"], stock: 18, image: "https://images.pexels.com/photos/11326180/pexels-photo-11326180.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 22, name: "Minimalist Steel Watch", section: "Accessories", category: "Watches", price: 79.99, oldPrice: 109.99, discount: 27, rating: 4.8, reviews: 176, description: "Slim stainless steel watch with a sapphire-coated crystal and 5ATM water resistance.", sizes: [], colors: ["Silver", "Rose Gold"], stock: 32, image: "https://images.pexels.com/photos/128206/pexels-photo-128206.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 23, name: "Classic Aviator Sunglasses", section: "Accessories", category: "Sunglasses", price: 34.99, oldPrice: 44.99, discount: 22, rating: 4.5, reviews: 112, description: "Timeless aviator frames with polarized lenses and full UV400 protection.", sizes: [], colors: ["Gold/Green", "Black/Grey"], stock: 44, image: "https://images.pexels.com/photos/157842/pexels-photo-157842.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 24, name: "Embroidered Baseball Cap", section: "Accessories", category: "Caps", price: 19.99, oldPrice: 24.99, discount: 20, rating: 4.4, reviews: 58, description: "Structured cotton twill cap with an adjustable strap and embroidered logo detail.", sizes: ["One Size"], colors: ["Black", "Stone"], stock: 51, image: "https://images.pexels.com/photos/12712906/pexels-photo-12712906.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 25, name: "Genuine Leather Belt", section: "Accessories", category: "Belts", price: 29.99, oldPrice: 39.99, discount: 25, rating: 4.6, reviews: 84, description: "Full-grain leather belt with a brushed nickel buckle. Ages beautifully with wear.", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Brown"], stock: 37, image: "https://images.pexels.com/photos/31432650/pexels-photo-31432650.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 26, name: "Canvas Crossbody Bag", section: "Accessories", category: "Bags", price: 44.99, oldPrice: 54.99, discount: 18, rating: 4.5, reviews: 63, description: "Durable canvas crossbody with leather trim and adjustable strap for hands-free days.", sizes: [], colors: ["Olive", "Navy"], stock: 25, image: "https://images.pexels.com/photos/157888/pexels-photo-157888.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: true },
  { id: 27, name: "Signature Eau de Parfum", section: "Accessories", category: "Perfumes", price: 64.99, oldPrice: 84.99, discount: 24, rating: 4.7, reviews: 145, description: "A warm, woody signature scent with notes of bergamot, cedar and amber. 50ml.", sizes: [], colors: [], stock: 30, image: "https://images.pexels.com/photos/3785784/pexels-photo-3785784.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 28, name: "Denim Trucker Jacket", section: "Men", category: "Jackets", price: 64.99, oldPrice: 84.99, discount: 24, rating: 4.6, reviews: 79, description: "Classic trucker silhouette in rigid denim that softens beautifully with wear.", sizes: ["S", "M", "L", "XL"], colors: ["Light Wash", "Dark Wash"], stock: 24, image: "https://images.pexels.com/photos/457445/pexels-photo-457445.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 29, name: "Oversized Check Blazer", section: "Women", category: "Blazers", price: 84.99, oldPrice: 109.99, discount: 23, rating: 4.4, reviews: 52, description: "Relaxed oversized blazer in a subtle check, styled to layer over everything.", sizes: ["XS", "S", "M", "L"], colors: ["Grey Check"], stock: 20, image: "https://images.pexels.com/photos/8832933/pexels-photo-8832933.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false },
  { id: 30, name: "Zip-Up Hoodie", section: "Men", category: "Hoodies", price: 47.99, oldPrice: 62.99, discount: 24, rating: 4.5, reviews: 91, description: "Midweight zip hoodie with a kangaroo pocket and adjustable drawcord hood.", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Black", "Heather Grey"], stock: 38, image: "https://images.pexels.com/photos/10971114/pexels-photo-10971114.jpeg?auto=compress&cs=tinysrgb&w=600&h=750&fit=crop", featured: false }
];

// ---------- Shared helper functions used across pages ----------

function getProductById(id) {
  return PRODUCTS.find(p => p.id === Number(id));
}

function getFeaturedProducts(limit = 8) {
  return PRODUCTS.filter(p => p.featured).slice(0, limit);
}

function getRelatedProducts(product, limit = 4) {
  return PRODUCTS
    .filter(p => p.id !== product.id && (p.section === product.section || p.category === product.category))
    .slice(0, limit);
}

function formatPrice(value) {
  return `GH₵${Number(value).toFixed(2)}`;
}

function renderStars(rating) {
  const full = Math.round(rating);
  let html = '';
  for (let i = 1; i <= 5; i++) {
    html += i <= full ? '★' : '☆';
  }
  return `<span class="stars" aria-label="${rating} out of 5 stars">${html}</span>`;
}